apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: grpcdemo-server
  namespace: grpcdemo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~0
spec:
  helmVersion: v2
  releaseName: grpcdemo-server
  chart:
    git: git@github.com:jtmilanest/grpcdemo
    ref: master
    path: helm/grpcdemo-server
  values:
    replicaCount: 1